controller_manager:
  ros__parameters:
    update_rate: 100  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# ----------------------------------------------------------------------
# Configurazione Cinematica DIFFERENZIALE
# ----------------------------------------------------------------------
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["rear_left_wheel_joint", "front_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint", "front_right_wheel_joint"]
    wheels_per_side: 2
    wheel_separation: 0.14
    wheel_radius: 0.045
    base_frame_id: base_link
    odom_frame_id: odom
    position_feedback: true
    enable_odom_tf: false #todo: should be ok check the docs for this
    use_stamped_vel: true

# ----------------------------------------------------------------------
# Configurazione Cinematica ACKERMANN
# ----------------------------------------------------------------------
ackermann_steering_controller:
  ros__parameters:
    wheelbase: 0.2
    front_wheel_track: 0.14
    rear_wheel_track: 0.14
    front_wheels_radius: 0.045
    rear_wheels_radius: 0.045
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    front_wheels_names: ['right_wheel_steering_joint', 'left_wheel_steering_joint']
    use_stamped_vel: true  # Nota: questo cambierà il topic in /reference_stamped
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false
    twist_covariance_diagonal: [0.001, 0.001, 1e6, 1e6, 1e6, 0.01]
    pose_covariance_diagonal: [0.001, 0.001, 1e6, 1e6, 1e6, 0.01]
    position_feedback: false