<?xml version="1.0"?>
<package format="3">
  <name>limo_bringup</name>
  <version>0.0.0</version>
  <description>Bringup launch e configurazione per il robot LIMO (Nav2 + SLAM Toolbox)</description>
  <maintainer email="hansolo@notarealadress.com">hansolo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_python</depend> 
  <depend>launch</depend> 
  <depend>launch_ros</depend>
  <depend>nav2_bringup</depend>
  <depend>rviz2</depend>
  <depend>slam_toolbox</depend>
  <depend>twist_stamper</depend>

  <depend>limo_description</depend>
  <depend>limo_car</depend>

  <!-- Plugin Nav2, ricordati di aggiungerli! -->
  <depend>nav2_smac_planner</depend>
  <depend>nav2_regulated_pure_pursuit_controller</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
